<?xml version='1.0'?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version='1.0'>

<!--########################Files to Include######################-->

<!-- Importing the Norman Walsh's stylesheet as the basis. -->
<xsl:import href="1.79.2/html/chunk.xsl"/>
<!-- see NOTE ABOUT PATHS in README file for details -->

<!--####################### HTML Parameters   ####################-->

<xsl:param name="use.id.as.filename">1</xsl:param>
<xsl:param name="chunker.output.encoding">UTF-8</xsl:param>
<xsl:param name="xref.with.number.and.title">0</xsl:param>

<!--####################### Files to Include  ####################-->

<!-- Including new title page stylesheets for customizing the placement 
     of tags in the title page. -->
<!-- This one is autogenerated from titlepage.xml -->
<!--<xsl:include href="titlepage.xsl"/> -->

<!-- This one was edited by hand, to make titlepage a separate chunk
     for book and aricle -->
<xsl:include href="html-titlepage2.xsl"/>

<!-- Make a separate titlepage and link it behind the main page. -->
<xsl:param name="generate.titlepage.link">1</xsl:param>

<!-- Makes the link to the titlepage. -->
<xsl:include href="html-chunk-common2.xsl"/> 

<!-- Changes appearance of Publisher. -->
<xsl:include href="html-publisher.xsl"/>

<!-- Changes appearance of "Revision history" -->
<xsl:include href="html-revhistory.xsl"/>

<!-- TOC labelling and generating and depth -->
<xsl:include href="html-toc.xsl"/>

<!-- Copyright years are a range. -->
<xsl:include href="html-copyright.xsl"/>

<!-- Admonition graphics and aligning title -->
<xsl:include href="html-admonitions.xsl"/>

<!-- Outputs Author (s):. -->
<xsl:include href="html-author.xsl"/>

<!-- Change presentation of othercredit. -->
<xsl:include href="html-othercredit.xsl"/>

<!-- Adds inline addresses inside the legalnotice. -->
<xsl:include href="html-legalnotice.xsl"/>

<!-- Italicizes the <sgmltag>releaseinfo</sgmltag>. -->
<xsl:include href="html-releaseinfo.xsl"/>

<!-- Bolds the <sgmltag>term</sgmltag> in the variable list. -->
<xsl:include href="html-variablelist.xsl"/>

<!-- Adds an informal procedure. -->
<xsl:include href="html-procedure.xsl"/>

<!-- Glossary customization. -->
<xsl:include href="html-glossary.xsl"/>

<!-- Defaults keycombo to a "+" -->
<xsl:include href="html-keycombo.xsl"/>


<!--  GnuCash common customization for HTML, PDF and so on. -->
<!--  This must be the last entry   -->
<xsl:include href="gnc-custom-common.xsl" />

</xsl:stylesheet>
